#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages
from subprocess import Popen, PIPE

def get_git_version():
    try:
        p = Popen(['git', 'describe', '--tags', '--always', '--dirty'],
                stdout=PIPE, stderr=PIPE)
        p.stderr.close()
        if p.wait() == 0:
            return p.stdout.readlines()[0].strip()
    except:
        pass
    raise AssertionError('Could not find the version number')

with open('README.rst') as f:
    readme = f.read()

def main():
    version = get_git_version()

    with open('pyaardvark/version.py', 'w') as f:
        f.write('# This file was autogenerated by setup.py\n')
        f.write('__version__ = \'%s\'\n' % (version,))

    setup(name = 'pyaardvark',
            version = version,
            description = 'Total Phase Aardvark library',
            long_description = readme,
            author = 'Michael Walle',
            author_email = 'michael.walle@kontron.com',
            packages = find_packages(),
            url = 'http://github.com/kontron/python-aardvark',
            license = 'LGPLv2+',
            classifiers = [
                'Development Status :: 4 - Beta',
                'Environment :: Console',
                'License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)',
                'Natural Language :: English',
                'Operating System :: OS Independent',
                'Programming Language :: Python :: 2',
                'Programming Language :: Python :: 2.7',
                'Topic :: Software Development :: Libraries :: Python Modules',
            ],
            entry_points = {
                'console_scripts': [
                    'aardvark = pyaardvark.cli_tool:main',
                ]
            },
            test_suite = 'tests',
    )

if __name__ == '__main__':
    main()
